parameters:
    warmup_min_fitness : 11
    n_iters : 10000
    trn_idx : 21
    tst_idx : 22


    tgt_class : '1-5-23_20_minicooper-luggage-minicar_5_1_1_nurbs' # 최하 에셋 PO
    savedir : './logs/'
    resized_res : 6
    json_path : './dataset/colmap_cameras_new.json'