parameters:
    warmup_min_fitness : 11
    n_iters : 10000
    trn_idx : 21
    tst_idx : 22


    tgt_class : '2-17-6_15_silver-round-streetlight_4_4_1_polygon'
    savedir : './logs/'
    resized_res : 6
    json_path : './dataset/colmap_cameras_new.json'