parameters:
    warmup_min_fitness : 11
    n_iters : 10000
    trn_idx : 21 # :19 라고하면 1~18 까지 슬라이싱 됨.
    tst_idx : 22 # 19번 째가 인덱싱됨. 


    tgt_class : '2-16-12_22_square-pillow-bean-bag_2_4_1_polygon' # 최하 에셋 PO
    savedir : './logs/'
    resized_res : 6
    json_path : './dataset/colmap_cameras_new.json'