parameters:
    warmup_min_fitness : 12
    n_iters : 20000
    trn_idx : 19 # :19 라고하면 1~18 까지 슬라이싱 됨.
    tst_idx : 19 # 19번 째가 인덱싱됨. 


    tgt_class : '2-21-2_7_retro-style-mint-oven_3_3_1_polygon' # 최하 에셋 PO
    savedir : './logs/'
    resized_res : 6
    json_path : './dataset/colmap_cameras.json'