parameters:
    warmup_min_fitness : 12
    n_iters : 10000
    trn_idx : 22 # :19 라고하면 1~18 까지 슬라이싱 됨.
    tst_idx : 22 # 19번 째가 인덱싱됨. 

    tgt_class : '2-14-10_24_Yellow-TopBottom-Solid-Square-Stool_1_2_1_nurbs' # 최하 에셋 PO
    savedir : './logs/'
    resized_res : 6
    json_path : './dataset/cameras.json'