parameters:
    warmup_min_fitness : 11
    n_iters : 10000
    trn_idx : 21
    tst_idx : 22

    tgt_class : '2-16-2_24_leather-white-wood-3+-seater-recliner_5_5_1_polygon' # 최하 에셋 PO
    savedir : './logs/'
    resized_res : 6
    json_path : './dataset/colmap_cameras_new.json'