parameters:
    warmup_min_fitness : 14
    n_iters : 5000
    trn_idx : 19 # :19 라고하면 1~18 까지 슬라이싱 됨.
    tst_idx : 19 # 19번 째가 인덱싱됨. 

    tgt_class : 'dog' # 최하 에셋 PO
    savedir : './logs/'
    resized_res : 6
    json_path : './dataset/dog_cameras.json'
